### ISSUE TITLE
Cordova Errors

### ISSUE THREAD

**Issue by strataga** [smooch/smooch-cordova#16]
$ meteor add cordova:io-smooch-smcordovaplugin@1.1.5  
Added Cordova plugin io-smooch-smcordovaplugin@1.1.5.
➜  vynomvp git:(master) ✗ meteor build ~/clients/builds/vynomvp --server=https://app.vno.mx
=> Errors executing Cordova commands:                                              

   While building Cordova app for platform Android:
   Error: /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed
   with exit code 8 Error output:

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:3:
   error: package io.smooch.core does not exist
   import io.smooch.core.*;
   ^

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:4:
   error: package io.smooch.ui does not exist
   import io.smooch.ui.ConversationActivity;
   ^

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:45:
   error: cannot find symbol
   ConversationActivity.show(this.cordova.getActivity());
   ^
   symbol:   variable ConversationActivity
   location: class SmoochCordova

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:52:
   error: cannot find symbol
   final User user = User.getCurrentUser();
   ^
   symbol:   class User
   location: class SmoochCordova

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:52:
   error: cannot find symbol
   final User user = User.getCurrentUser();
   ^
   symbol:   variable User
   location: class SmoochCordova

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:77:
   error: cannot find symbol
   User.getCurrentUser().addProperties(customProps);
   ^
   symbol:   variable User
   location: class SmoochCordova

   /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/src/io/smooch/cordova/SmoochCordova.java:88:
   error: cannot find symbol
   Smooch.track(eventName);
   ^
   symbol:   variable Smooch
   location: class SmoochCordova
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use unchecked or unsafe operations.
   Note: Recompile with -Xlint:unchecked for details.
   7 errors

   FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileArmv7ReleaseJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  
  /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
  throw e;
  ^
  Error code 1 for command: /Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/gradlew with
  args:
  cdvBuildRelease,-b,/Users/jcochran/clients/vynomvp/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
  at ChildProcess.whenDone
  (/Users/jcochran/.meteor/packages/meteor-tool/.1.1.10.c6ilhh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:766:16)
  at Socket.<anonymous> (child_process.js:979:11)
  at Socket.emit (events.js:95:17)
  at Pipe.close (net.js:466:12)

@cosio55

**Comment by edchan77** [comment]
Is this meteor specific? @appjitsu

**Comment by jugarrit** [comment]
This looks like a problem importing the dependencies.
It seems like you might not have the packages included correctly.

Please read and add the [Android Studio with Gradle](http://docs.smooch.io/android/#adding-smooch-to-your-app) section and try again.

Hope that helps.

Julian
