### ISSUE TITLE
How to setup userId and login

### ISSUE THREAD

**Issue by jerocosio** [smooch/smooch-cordova#18]
Hi, I'm trying to add the userId so that my users can continue the conversation on different devices, but I don't see this feature on Smooch Cordova, is there a way to add it? Thanks in advance!

**Comment by svs** [comment]
+1.

**Comment by janpio** [comment]
Would this be the relevante iOS and Android code parts?

http://docs.smooch.io/android/#users-on-multiple-devices
http://docs.smooch.io/ios/#users-on-multiple-devices

Shouldn't be too hard to add this to the plugin code...
