### ISSUE TITLE
Using web installation

### ISSUE THREAD

**Issue by okpatil4u** [smooch/smooch-cordova#19]
If I use web installation method with cordova index.html file, it works properly. Doesn't this repo become obsolete then ?

**Comment by janpio** [comment]
I expected the iOS and Android SKDs to be implemented natively and so being more performant and integratable compared to the JS/web option. Isn't this the case?

**Comment by okpatil4u** [comment]
In my case using smooch as a script was a better decision than installing
native sdk. I still have problems with android notifications not being sent
from slack, and having to redesign my app to leave a small footer space for
smooch popup. But it works smoothly. This might not be case with everyone.

**Comment by janpio** [comment]
Thanks for the feedback.

Then it seems you are right - it actually is a valid choice not to use this plugin but use the web version for a quick implementation.

**Comment by okpatil4u** [comment]
But there is still some problem with push notifications and slack, it seems that I cannot send push notifications on android with slack with smooch script in index.html. Does anyone else face this problem ?

**Comment by klh** [comment]
use the slack cordova integrations and catch the notfiication through there?

**Comment by jugarrit** [comment]
Hey there!
Using the script in `index.html` will definitely result in a poorer experience than using the plugin.
You won't get any push notifications on the device because that script doesn't run any native Android code whatsoever, and as mentioned by @piotrowski it will definitely be less performant than the SDK.
