### ISSUE TITLE
Should mention to manually load www/smooch-cordova.js

### ISSUE THREAD

**Issue by guyschlider** [smooch/smooch-cordova#21]
Hi,

During the first time trying to use this plugin I had to find out by myself that the plugin isn't being added to cordova_plugins.js and I need to manually load www/smooch-cordova.js in my index.html.

You might want to mention it in the README file or add to the plugin.xml the line that actually loads the js automatically (I think its called <js-module> in the plugin.xml)

Thanks for this plugin though :)

**Comment by jugarrit** [comment]
I actually now automatically load the plugin! Thanks for the idea ;)
