### ISSUE TITLE
Is this a first class intergation method for smooch?

### ISSUE THREAD

**Issue by janpio** [smooch/smooch-cordova#23]
Looking at the issues and open PR I am not 100% sure smooch-cordova is in the focus of you guys. As we are just evaluating you and you market colleagues (competitors...) to add to a set of Ionic/Cordova apps this is quite important for me to know.

What's the plan for the future of smooch-cordova?

(Basically I am checking if anybody is reading the issues at all in a timely manner :p)

**Comment by dannytranlx** [comment]
We will try to pick this up a little bit. Sorry for the delays!

**Comment by janpio** [comment]
That would be great.

Still the question: Is Cordova integration a focus of you? Do you plan to support this going on? Should we invest time and money to integrate this?

**Comment by klh** [comment]
they need to simplify their installation process immensely, this will not fly with a phonegap / ioni based app where the platform code is built dynamically.

@dannytranlx any timeline or guidance on this from you guys?

**Comment by jugarrit** [comment]
Sorry for the lack of activity on this repo!

To answer the question, this integration method is supported insofar as we want it to always be working correctly, but we are not investing a lot of time into improving it.

It does need some love, however, and we will definitely respond to any pull requests created by the community.
