### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by vaibhavn1** [smooch/smooch-cordova#24]
Hi team

You a got a great product. Excited to implement it.

I followed all the steps mentioned in the readme file but getting the following error during the build process.

:compileDebugJavaWithJavacC:\Users\XYZ\Desktop\App\XYZ\platfo
rms\android\src\com\XYZ\android\MainApplication.java:5: error: package
io.smooch.core does not exist
import io.smooch.core.Smooch;
                     ^
C:\Users\XYZ\Desktop\App\XYZ\platforms\android\src\io\smooch\
cordova\SmoochCordova.java:3: error: package io.smooch.core does not exist
import io.smooch.core.*;
^
C:\Users\XYZ\Desktop\App\XYZ\platforms\android\src\io\smooch\
cordova\SmoochCordova.java:4: error: package io.smooch.ui does not exist
import io.smooch.ui.ConversationActivity;

It will be great if you could provide a quick response.

Regards

Vaibhav

**Comment by jugarrit** [comment]
Did you also follow the instructions located [here](http://docs.smooch.io/android/#adding-smooch-to-your-app)?

It seems like you do not have the packages included correctly.
Please read and add the Android Studio with Gradle section and try again.

Hope that helps.

Julian

**Comment by vaibhavn1** [comment]
Thanks for the swift response man...
