### ISSUE TITLE
Unable to fetch plugin from "phonegap plugin add"

### ISSUE THREAD

**Issue by sisodiakaran** [smooch/smooch-cordova#27]
Hi,

I am trying to setup plugin in my phonegap project. When I execute `phonegap plugin add cordova-plugin-smooch`

```
$ phonegap plugin add cordova-plugin-smooch
Fetching plugin "cordova-plugin-smooch" via npm

Error: Failed to fetch plugin cordova-plugin-smooch via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-smooch

```

Is there any step which I am missing?

Thanks,
Karan

**Comment by jugarrit** [comment]
Hey Karan,

Please use phonegap plugin add smooch-cordova instead.
I will update the readme to reflect this. Sorry about that!

Julian

**Comment by sisodiakaran** [comment]
Thanks @jugarrit. Solution worked like a charm :)
