### ISSUE TITLE
Androidmanifest duplicate entry

### ISSUE THREAD

**Issue by Alphatiger** [smooch/smooch-cordova#29]
we are using phonegap-push plugin in our app.

when we installed smooch we started getting duplicate entry in androidmanifest.xml file 

Please let us know if this plugin is compatible with phonegap push plugin

**Comment by PvUtrix-zz** [comment]
Same question, this is an error from the build process for iOS

The following build commands failed:
    CompileC build/Tan.build/Debug-iphonesimulator/Tan.build/Objects-normal/i386/SmoochCordova.o Tan/Plugins/io-smooch-smcordovaplugin/SmoochCordova.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Pix/apps/tan/platforms/ios/cordova/build-debug.xcconfig,-project,Tan.xcodeproj,ARCHS=i386,-target,Tan,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Pix/apps/tan/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Pix/apps/tan/platforms/ios/build/sharedpch

**Comment by jugarrit** [comment]
This will quite possibly be fixed when we update to FCM.

**Comment by jugarrit** [comment]
Please try the latest version of the plugin and open this again if the problem persists.
