### ISSUE TITLE
fatal error: 'Smooch/Smooch.h' file not found

### ISSUE THREAD

**Issue by jesperbruunhansen** [smooch/smooch-cordova#33]
Hi Smooch,

When I build my project I get this error:

```
.../platforms/ios/app-name/Plugins/cordova-plugin-smooch/SmoochCordova.m:10:9: fatal error: 'Smooch/Smooch.h' file not found
#import <Smooch/Smooch.h>
```

I have installed the plugin with:
`cordova plugin add smooch-cordova`

Is there anything more to be done, before the build process should be able to run?

Jesper.

**Comment by BloodMoonShard** [comment]
How resolve same problem?

**Comment by glasset** [comment]
you just need to add [Smooch.framework](https://github.com/smooch/smooch-ios) in your project.
