### ISSUE TITLE
Cordova Android Example

### ISSUE THREAD

**Issue by vaibhavn1** [smooch/smooch-cordova#8]
Hi 

Can you guys upload a demo project for intergration with cordova android. As instructions are not very clear. It would be very helpful as cordova developers usually dont have native experience. I am confused with the application part step where init function needs to called.

Regards

Vaibhav

**Comment by vaibhavn1** [comment]
Hi Team,

Any update on this?

Regards

Vaibhav

**Comment by edchan77** [comment]
Howdy! You can check out the example project I just uploaded and the code in https://github.com/supportkit/supportkit-cordova/blob/master/example/android/src/com/example/hello/MainApplication.java
You'll notice that lives along side of MainActivity.

Let me know if this helps!
