### ISSUE TITLE
Error in SupportKitCordova.m

### ISSUE THREAD

**Issue by jerocosio** [smooch/smooch-cordova#9]
Hi, there is an error on the file SupportKitCordva.m on line 61, there is a ']' missing, the code should be like:

```
- (void)setUser:(CDVInvokedUrlCommand *)command {
    NSDictionary *user = [command argumentAtIndex:0];

    SKTUser *currentUser = [SKTUser currentUser];
    [currentUser setValuesForKeysWithDictionary:user];

    id timestamp = [user valueForKey:@"signedUpAt"];
    if (timestamp && [timestamp isKindOfClass:[NSNumber class]]) {
        NSTimeInterval seconds = [timestamp doubleValue] / 1000; // covert from milliseconds to seconds
        [currentUser setSignedUpAt:[NSDate dateWithTimeIntervalSince1970:seconds]];
    }
}
```

**Comment by edchan77** [comment]
hm.. I fixed it a little while ago: https://github.com/supportkit/supportkit-cordova/commit/92587858be2c1d23d283835570fad7bea2a7bb7d

Did you recently pull in the code?

**Comment by jerocosio** [comment]
I am using Meteor, and it uses NPM for the cordova plugins, so I think it should download the latest version (1.1.13 ?), to add it on Meteor I used:

meteor add cordova:io-supportkit-sktcordovaplugin@1.1.3

**Comment by jerocosio** [comment]
Y think it's an error in Meteor, but please take a look a this fork:

https://github.com/cosio55/supportkit-cordova

with this you don't need to add any libraries or files in Xcode because the plugin loads them directly, can I send you a pull request?

**Comment by edchan77** [comment]
hey @cosio55 nice! But I wouldn't include the Supportkit frameworks directly because it won't stay up-to-date. However, maybe it can pull in the main repo directly.

**Comment by jerocosio** [comment]
Hey @edchan77 I made some changes to the recent Smooch, check this fork again, I think you can include the Android installation directly using this plugin, and also there is a better way to add the JS files, check it out: https://github.com/cosio55/smooch-cordova

**Comment by jerocosio** [comment]
Hey @edchan77 I made a new pull request, so that we can add the Android dependencies from the plugin.

**Comment by jugarrit** [comment]
Thanks @cosio55!
I've made many updates to the installation procedure based on some of what you did in your fork.

**Comment by jerocosio** [comment]
Amazing! @jugarrit I hope this makes it easier to add SupportKit to any Cordova app.
